server:
  port: 8081

# department service should go and connect to the below URL
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# zipkin
management:
  tracing:
    sampling:
      probability: 1.0